// games.js
const juegos = [
  { name: "Level Devil", url: "https://level-devil.io/game/level-devil/", img: "assets/games/level-devil.png" },
  { name: "Drive Mad", url: "https://drive-madgame.github.io/file/", img: "assets/games/drive-mad.jpeg" },
  { name: "Longcat", url: "https://play.fancade.com/5BFC1C2A246D67DD?mp_assets=https://s2.minijuegosgratis.com/&mp_embed=0&mp_game&mp_game_id=252905&mp_game_uid=longcat", img: "assets/games/long_cat.png" },
  { name: "Stick fighter", url: "https://labgstore21.github.io/g2/class-629/", img: "assets/games/stick-fighter.jpeg" },
  { name: "Suika Game", url: "https://suikagame.io/game/suika-game/", img: "assets/games/suika-game.jpg" },
  { name: "Merge Rot", url: "https://game.azgame.io/merge-brainrot/", img: "assets/games/merge-rot.png" },
  { name: "Motox3m", url: "https://nb-ga.github.io/games-site/projects/moto-x3m/index.html", img: "assets/games/moto-x3m.png" },
  { name: "Stickman Hook", url: "https://ug17.github.io/play/Stickman-HookUB/", img: "assets/games/stickman-hook.png" },
  { name: "Monkey Mart", url: "https://monkey-mart.io/iframe/index.html", img: "assets/games/monkey-mart.png" },
  { name: "My perfect hotel", url: "https://1games.io/game/perfect-hotel/", img: "assets/games/my-perfect-hotel.jpg" },
  { name: "Bascket random", url: "https://games-site.github.io/projects/basket-random/frame.html", img: "assets/games/bascket_random.png" },
  { name: "Boxing random", url: "https://games-site.github.io/projects/boxing-random/frame.html", img: "assets/games/boxing_random.png" },
  { name: "Soccer random", url: "https://games-site.github.io/projects/soccer-random/frame.html", img: "assets/games/soccer_random.png" },
  { name: "Volley random", url: "https://games-site.github.io/projects/volley-random/frame.html", img: "assets/games/volley-random.jpg" },
  { name: "Crossy Road", url: "https://crossy-road.gitlab.io/file/", img: "assets/games/crossy-road.jpg" },
  { name: "Paper.io 2", url: "https://nb-ga.github.io/games-site/projects/paperio2/index.html", img: "assets/games/paper.io_2.png" },
  { name: "Police Chase", url: "https://trafficrally.io/blacktop-police-chase.embed", img: "assets/games/police-chase.jpg" },
  { name: "Stack", url: "https://ug17.github.io/play/Stack/", img: "assets/games/stack.jpeg" },
  { name: "Minecraft Launcher", url: "https://yee.pages.dev/", img: "assets/games/minecraft-launcher.png" },
  { name: "Flappy Bird", url: "https://nb-ga.github.io/games-site/projects/flappy-bird/index.html", img: "assets/games/flappy_bird.png" },
  { name: "2048", url: "https://nb-ga.github.io/games-site/projects/2048/index.html", img: "assets/games/2048.png" },
  { name: "Motox3m 2", url: "https://nb-ga.github.io/games-site/projects/moto-x3m-2/index.html", img: "assets/games/motox3m_2.png" },
  { name: "Motox3m Winter", url: "https://games-site.github.io/projects/moto-x3m-winter/index.html", img: "assets/games/moto-x3m-4-winter.png" },
  { name: "Motox3m Spooky Land", url: "https://games-site.github.io/projects/moto-x3m-spooky-land/index.html", img: "assets/games/moto-x3m-spooky-land.png" },
  { name: "Motox3m Pool Party", url: "https://games-site.github.io/projects/moto-x3m-pool-party/index.html", img: "assets/games/moto-x3m-5-pool-party.png" },
  { name: "Ball Sort", url: "https://games-site.github.io/projects/ball-sort-puzzle/index.html", img: "assets/games/ball-sort.png" },
  { name: "Fnaf 1", url: "https://run3.io/popgame/fnaf/fnaf1/", img: "assets/games/fnaf1.jpg" },
  { name: "Fnaf 2", url: "https://nb-ga.github.io/games-site/projects/fnaf-2/index.html", img: "assets/games/fnaf2.png" },
  { name: "Fnaf 3", url: "https://nb-ga.github.io/games-site/projects/fnaf-3/index.html", img: "assets/games/fnaf3.png" },
  { name: "Fnaf 4", url: "https://games-site.github.io/projects/fnaf-4/index.html", img: "assets/games/fnaf4.png" },
  { name: "Fnaf Sister Location", url: "https://games-site.github.io/projects/fnaf-5/index.html", img: "assets/games/fnaf5.png" },
  { name: "Subway Surfers", url: "https://ug17.github.io/play/Subway-Surfers/", img: "assets/games/subway-surfers.png" },
  { name: "Subway Surfers winter holiday", url: "https://ubg77.github.io/updatefaqs/subway-surfers-winter-holiday/", img: "assets/games/subway-surfers-winter-holiday.png" },
  { name: "Subway Surfers New York", url: "https://ubg77.github.io/updatefaqs/subway-surfers-nyc/", img: "assets/games/subway-surfers-nyc.png" },
  { name: "Subway Surfers Bali", url: "https://ubg77.github.io/updatefaqs/subway-surfers-bali/", img: "assets/games/subway-surfers-bali.png" },
  { name: "Temple Run", url: "https://templerun.org/wp-content/uploads/games/html5/T/Temple%20Game%20Jungle/index.html", img: "assets/games/temple-run.jpg" },
  { name: "Friday Night Funkin", url: "https://fnf.kdata1.com/2025/fnf/7500/", img: "assets/games/fnf.jpg" },
  { name: "Power Pamplona", url: "https://www.friv.com/z/games/powerpamplona/game.html", img: "assets/games/power-pamplona.jpeg" },
  { name: "Boxing Stars", url: "https://www.friv.com/z/games/boxingstars/game.html", img: "assets/games/boxing-stars.jpeg" },
  { name: "Bad Ice cream 2", url: "https://onegamez.github.io/bad-ice-cream-2/", img: "assets/games/bad-ice-cream-2.jpeg" },
  { name: "Bad Ice cream 3", url: "https://onegamez.github.io/bad-ice-cream-3/", img: "assets/games/bad-ice-cream-3.jpeg" },
  { name: "Steal a Brainrot", url: "https://st.8games.net/9/8g/igra-ukradi-brejnrot-original-3d/", img: "assets/games/steal-a-brainrot.jpeg" },
  { name: "Plants vs Brainrots", url: "https://st.8games.net/7/8g/igra-brejnroty-protiv-rastenij/", img: "assets/games/plants-vs-brainrots.jpg" },
  { name: "Geometry Dash", url: "https://1games.io/game/geometry-lite/", img: "assets/games/geometry-dash.jpeg" },
  { name: "Geometry Vibes", url: "https://files.twoplayergames.org/files/games/g1/geometry-vibes-v11/index.html", img: "assets/games/geometry-vibes.jpg" },
  { name: "Harvest Simulator", url: "https://g.igroutka.ru/games/1213/jtFMmdAVoke2w6qL/d8d9f2cc-186e-4695-adce-1ef984e47d59/index.html", img: "assets/games/harvest-simulator.png" },
  { name: "That's not my neighbor", url: "https://gnhustgames.github.io/class-73/thats-not-my-neighbor/", img: "assets/games/thats-not-my-neighbor.jpg" },
  { name: "Gta Chinatown", url: "https://retrogamesonline.io/grand-theft-auto-chinatown-wars-usa-enfrdeesit.embed", img: "assets/games/gta-chinatown.jpeg" },
  { name: "Head Soccer 2024", url: "https://1games.io/game/head-soccer-2024/", img: "assets/games/head-soccer-2024.jpeg" },
  { name: "Rubik", url: "https://rubikscu.be/", img: "assets/games/rubik.png" },
  { name: "Bottle Jump", url: "https://1games.io/game/bottle-jump/", img: "assets/games/bottle-jump.jpeg" },
  { name: "Brain Test", url: "https://23azostore.github.io/s2/brain-test-2-tricky-stories/", img: "assets/games/brain-test.jpeg" },
  { name: "Cut the Rope", url: "https://games-site.github.io/projects/ctr-time-travel/index.html", img: "assets/games/cut-the-rope.png" },
  { name: "Papery Planes", url: "https://games-site.github.io/projects/papery-planes/index.html", img: "assets/games/papery-planes.png" },
  { name: "Chill guy clicker", url: "https://game.azgame.io/chill-guy-clicker/", img: "assets/games/chill-guy-clicker.jpg" },
  { name: "Cookie Clicker", url: "https://azgames.io/cookie-clicker.embed", img: "assets/games/cookie-clicker.jpg" },
  { name: "Sprunki Clicker", url: "https://sprunkiclicker.io/", img: "assets/games/sprunki-clicker.jpg" },
  { name: "Sprunki", url: "https://azgames.io/game/sprunki/", img: "assets/games/sprunki.jpg" },
  { name: "Jetski race", url: "https://1games.io/game/jetski-race/", img: "assets/games/jetski-race.jpg" },
  { name: "Deer adventure", url: "https://game.azgame.io/deer-adventure/", img: "assets/games/deer-adventure.jpg" },
  { name: "Dude Theft Auto", url: "https://1games.io/game/dude-theft-auto/", img: "assets/games/dude-theft-auto.jpg" },
  { name: "Fireboy & Watergirl 1", url: "https://games-site.github.io/projects/fireboy-and-watergirl-1/index.html", img: "assets/games/fireboy&watergirl_1.jpg" },
  { name: "Fireboy & Watergirl 2", url: "https://games-site.github.io/projects/fireboy-and-watergirl-2/index.html", img: "assets/games/fireboy&watergirl_2.jpg" },
  { name: "Fireboy & Watergirl 3", url: "https://games-site.github.io/projects/fireboy-and-watergirl-3/index.html", img: "assets/games/fireboy&watergirl_3.jpg" },
  { name: "Fireboy & Watergirl 4", url: "https://games-site.github.io/projects/fireboy-and-watergirl-4/index.html", img: "assets/games/fireboy&watergirl_4.jpg" },
  { name: "Fireboy & Watergirl 5", url: "https://games-site.github.io/projects/fireboy-and-watergirl-5/index.html", img: "assets/games/fireboy&watergirl_5.jpg" },
  { name: "Fireboy & Watergirl 6", url: "https://games-site.github.io/projects/fireboy-and-watergirl-6/index.html", img: "assets/games/fireboy&watergirl_6.jpg" },
  { name: "Billiards Master", url: "https://game.azgame.io/billiards-master/", img: "assets/games/billiards-master.jpg" },
  { name: "Block Blast 3D", url: "https://game.azgame.io/block-blast-3d/", img: "assets/games/block-blast-3d.jpg" },
  { name: "Snow Road 3D", url: "https://1games.io/game/snow-road-3d/", img: "assets/games/snow-road-3d.jpg" },
  { name: "Bike Xtreme", url: "https://azgames.io/bike-xtreme.embed", img: "assets/games/bike-xtreme.png" },
  { name: "Stickman Racing", url: "https://azgames.io/stickman-racing.embed", img: "assets/games/stickman-racing.jpg" },
  { name: "Plants vs Zombies", url: "https://kdata1.com/2024/05/pvz2scratch/", img: "assets/games/plants-vs-zombies.jpg" },
  { name: "Uno Online", url: "https://kdata1.com/2017/03/four-colors/", img: "assets/games/uno-online.jpg" },
  { name: "Stickman prison escape", url: "https://abinbins.github.io/a7/escaping-the-prison/", img: "assets/games/stickman-prison-escape.jpg" },
  { name: "Murder", url: "https://f.silvergames.com/ruffle/player.php?id=4462", img: "assets/games/murder.jpg" },
  { name: "Granny", url: "https://1games.io/game/granny-horror/", img: "assets/games/granny.jpg" },
  { name: "Plonky", url: "https://cdn.vietdp.com/file/vietdp-games/games/t52025/plonky/index.html", img: "assets/games/plonky.jpg" },
  { name: "Stickman Climb 2", url: "https://h5.ant.games/game-assets/17266550232074/index.html", img: "assets/games/stickman-climb-2.jpg" },
  { name: "Drift.io", url: "https://drift.io/", img: "assets/games/drift.io.png" },
  { name: "Traffic Escape", url: "https://fly.silvergames.com/m/traffic-escape/", img: "assets/games/traffic-escape.jpg" },
  { name: "Last chess standing", url: "https://playgroundfree.github.io/last-chess-standing/", img: "assets/games/last-chess-standing.jpg" },
  { name: "Blood Money!", url: "https://bloodmoney.1games.io/", img: "assets/games/blood-money.jpg" },
  { name: "Blood Money! 2", url: "https://1games.io/game/bloodmoney-2/", img: "assets/games/blood-money-2.png" },
  { name: "Scary teacher 3D", url: "https://g.igroutka.ru/games/1087/NgleEW1zP8YRpXGI/9d2ca9df-7f2c-4685-8907-e330be4ef190/index.html", img: "assets/games/scary-teacher-3d.jpg" },
  { name: "SchoolBoy Runaway", url: "https://st.8games.net/10/8g/igra-schoolboy-runaway/", img: "assets/games/school-boy-runaway.jpg" },
  { name: "Escape Road City 2", url: "https://1games.io/game/escape-road-city-2/", img: "assets/games/escape-road-city-2.jpg" },
  { name: "Ragdoll Archers", url: "https://bitlifeonline.github.io/ragdoll-archers/", img: "assets/games/ragdoll-archers.jpg" },
  { name: "Swipe Ball", url: "https://swipe-ball.1games.io/", img: "assets/games/swipe-ball.jpg" },
  { name: "Flick Goal", url: "https://playgroundfree.github.io/flick-goal/", img: "assets/games/flick-goal.png" },
  { name: "Fury Chase 2", url: "https://1games.io/game/fury-chase-2/", img: "assets/games/fury-chase-2.jpg" },
  { name: "Repo", url: "https://st.8games.net/10/8g/igra-repo-original/", img: "assets/games/repo.png" },
  { name: "Golf Hit", url: "https://golf-hit.1games.io/", img: "assets/games/golf-hit.jpg" },
  { name: "Dunk Dash", url: "https://1games.io/game/dunk-dash/", img: "assets/games/dunk-dash.jpg" },
  { name: "Icy Dash", url: "https://1games.io/game/icy-dash/", img: "assets/games/icy-dash.jpg" },
  { name: "Cat and Granny", url: "https://cdn.unblocked-games-free.com/games/4494/KQMUcZ73Nuneoj/390441/saesmjjdi8hyt0nhseqatqa5ku1gadbk/index.html", img: "assets/games/cat-and-granny.jpg" },
  { name: "Drive Beyond Horizons", url: "https://epicfreegames78.github.io/drive-beyond-horizons/", img: "assets/games/drive-beyond-horizons.jpg" },
  { name: "KoGaMa", url: "https://www.kogama.com/games/lagged/9231110/", img: "assets/games/kogama.png" },
  { name: "Fruit Ninja", url: "https://mountain658.github.io/g/fruitninja/fruitninja.html", img: "assets/games/fruit-ninja.png" },
  { name: "Kick the buddy", url: "https://st.8games.net/dasha1/igry-novye/igra-kik-ze-badi/", img: "assets/games/kick-the-buddy.jpg" },
  { name: "Raft Life", url: "https://freegames78.github.io/raft-life/", img: "assets/games/raft-life.jpg" },
  { name: "Stickman crazy box", url: "https://bitlifeonline.github.io/stickman-crazy-box/", img: "assets/games/stickman-crazy-box.jpg" },
  { name: "Ping Pong Go!", url: "https://g.igroutka.ru/games/606/UhpyYq1QGA0nBfjJ/48aab6e0-54af-4e2f-9379-f76fa99dc59a/index.html", img: "assets/games/ping-pong-go.jpg" },
  { name: "Super Mario Bros", url: "https://frivez.com/games/super-mario-bros/index.html", img: "assets/games/super-mario-bros.jpg" },
  { name: "Survival Race", url: "https://st.8games.net/14/igra-bitva-superkarov-3d/", img: "assets/games/survival-race.png" },
  { name: "Traffic rally", url: "https://1games.io/game/traffic-rally/", img: "assets/games/traffic-rally.png" },
  { name: "Brain lines", url: "https://1games.io/game/brain-lines/", img: "assets/games/brain-lines.jpg" },
  { name: "Poor Rabit", url: "https://newgamesdaily.github.io/poor-bunny/", img: "assets/games/poor-rabbit.jpg" },
  { name: "Basketball Stars", url: "https://basketball-stars.io/game/basketball-stars/", img: "assets/games/basketball-stars.jpg" },
  { name: "Bounce Up", url: "https://bounce-up.1games.io/", img: "assets/games/bounce-up.png" },
  { name: "Stickman Empires", url: "https://stickman-empires.1games.io/", img: "assets/games/stickman-empires.jpg" },
  { name: "Jump Up", url: "https://1games.io/game/jump-up/", img: "assets/games/jump-up.png" },
  { name: "Merge Arena", url: "https://bitlifeonline.github.io/merge-arena/", img: "assets/games/merge-arena.png" },
  { name: "Penalty Shootout Multi League", url: "https://bitlifeonline.github.io/penalty-shootout-multi-league/", img: "assets/games/penalty-shootout-multi-league.png" },
  { name: "Gobattle", url: "https://bitlifeonline.github.io/gobattle/", img: "assets/games/gobattle.png" },
  { name: "Canon Blast", url: "https://bitlifeonline.github.io/cannon-blast/", img: "assets/games/canon-blast.png" },
  { name: "Dino Bros", url: "https://bitlifeonline.github.io/dino-bros/", img: "assets/games/dino-bros.png" },
  { name: "Obby parkour ultimate", url: "https://bitlifeonline.github.io/obby-parkour-ultimate/", img: "assets/games/obby-parkour-ultimate.png" },

];
  








